# Generated by Django 4.1.5 on 2023-01-20 19:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationCard',
            fields=[
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('translate_request', models.TimeField(blank=True, max_length=2000, null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='uploaded')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
